# Generated by Django 5.1.6 on 2026-08-18 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BannedIP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.GenericIPAddressField(db_index=True, unique=True)),
                ("reason", models.CharField(blank=True, max_length=64)),
                ("is_permanent", models.BooleanField(default=False)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Empty together with permanent means forever; otherwise the deadline.",
                        null=True,
                    ),
                ),
                ("hit_count", models.PositiveIntegerField(default=0)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "banned IP",
                "verbose_name_plural": "banned IPs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SecurityEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.GenericIPAddressField(db_index=True)),
                ("user_agent", models.CharField(blank=True, max_length=512)),
                ("method", models.CharField(blank=True, max_length=8)),
                ("path", models.CharField(blank=True, max_length=512)),
                ("referer", models.CharField(blank=True, max_length=512)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("waf_sqli", "waf_sqli"),
                            ("waf_xss", "waf_xss"),
                            ("waf_path", "waf_path"),
                            ("waf_cmd", "waf_cmd"),
                            ("bot_ua", "bot_ua"),
                            ("bot_headless", "bot_headless"),
                            ("bot_no_headers", "bot_no_headers"),
                            ("rate_limit", "rate_limit"),
                            ("honeypot_url", "honeypot_url"),
                            ("honeypot_form", "honeypot_form"),
                            ("brute_force", "brute_force"),
                            ("scraper", "scraper"),
                            ("csp_violation", "csp_violation"),
                            ("ip_banned", "ip_banned"),
                            ("ban_lifted", "ban_lifted"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "severity",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (10, "low"),
                            (20, "medium"),
                            (30, "high"),
                            (40, "critical"),
                        ],
                        db_index=True,
                        default=20,
                    ),
                ),
                (
                    "payload_snippet",
                    models.CharField(
                        blank=True,
                        help_text="The fragment that matched, taken from the URL or body (max 500 chars).",
                        max_length=500,
                    ),
                ),
                (
                    "blocked",
                    models.BooleanField(
                        default=False,
                        help_text="True when the request was rejected; False when it was only logged.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "security event",
                "verbose_name_plural": "security events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at", "severity"],
                        name="bnc_evt_recent_sev_idx",
                    ),
                    models.Index(
                        fields=["ip", "-created_at"], name="bnc_evt_ip_recent_idx"
                    ),
                ],
            },
        ),
    ]
